language: csharp
dist: trusty
sudo: required
mono: none
dotnet: 2.2

install:
- dotnet restore

script:
- dotnet build
- dotnet test Trendyol.Tests/Trendyol.Tests.csproj

global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1
